create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default '',phone text,nik text,role text not null default 'customer' check(role in('customer','admin')),level text not null default 'buyer' check(level in('buyer','member','agent','distributor')),referral_parent_id uuid references public.profiles(id),referral_code text unique,points_available bigint not null default 0,deposit_paid numeric(14,2) not null default 0,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.referral_codes(id uuid primary key default gen_random_uuid(),code text not null unique,owner_id uuid not null references public.profiles(id) on delete cascade,active boolean not null default true,is_primary boolean not null default false,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(),name text not null unique,description text,price numeric(14,2) not null,member_discount numeric(14,2) not null default 2000,agent_price numeric(14,2),distributor_price numeric(14,2),stock numeric(14,2) not null default 0,points int not null default 500,active boolean not null default true,created_at timestamptz not null default now());
insert into public.products(name,price,stock,points,member_discount) values ('TM',140000,49,500,2000),('TM NAT E',180000,2,500,2000),('ASSIKA HABBATS',250000,47.5,500,2000),('ASSIKA GOLD',350000,1,500,2000),('CK',230000,3,500,2000) on conflict(name) do update set price=excluded.price,points=excluded.points,member_discount=excluded.member_discount;
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),order_no text not null unique,buyer_id uuid not null references public.profiles(id),upline_id uuid references public.profiles(id),recipient text not null,phone text not null,address text not null,postal_code text,subtotal numeric(14,2) not null default 0,shipping_cost numeric(14,2) not null default 0,total numeric(14,2) not null default 0,shipping_method text,tracking_no text,va_bank text,va_number text,payment_reference text,status text not null default 'pending_payment' check(status in('pending_payment','paid','processing','shipped','completed','cancelled','refunded')),points_released boolean not null default false,created_at timestamptz not null default now(),paid_at timestamptz,completed_at timestamptz);
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid not null references public.products(id),qty numeric(14,2) not null check(qty>0),unit_price numeric(14,2) not null,points_each int not null default 500);
create table if not exists public.points_ledger(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id),order_id uuid references public.orders(id),points bigint not null,type text not null,note text,created_at timestamptz not null default now());
create table if not exists public.withdrawals(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id),points bigint not null,amount_rupiah numeric(14,2) not null,destination text not null,status text not null default 'pending' check(status in('pending','paid','rejected')),created_at timestamptz not null default now(),processed_at timestamptz,processed_by uuid references public.profiles(id));
create table if not exists public.support_tickets(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id),subject text not null,message text not null,status text not null default 'open',created_at timestamptz not null default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare lvl text:=coalesce(new.raw_user_meta_data->>'level','buyer'); upl_code text:=nullif(upper(trim(coalesce(new.raw_user_meta_data->>'upline_code',''))),''); upl uuid; code text; begin if lvl not in('buyer','member','agent','distributor') then lvl:='buyer'; end if; if lvl<>'buyer' then if nullif(new.raw_user_meta_data->>'nik','') is null then raise exception 'NIK wajib'; end if; if upl_code is null then raise exception 'Kode upline wajib'; end if; select owner_id into upl from public.referral_codes where upper(code)=upl_code and active=true limit 1; if upl is null then raise exception 'Kode upline tidak valid'; end if; end if; code:='JVN-'||upper(substr(replace(new.id::text,'-',''),1,8)); insert into public.profiles(id,full_name,phone,nik,level,referral_parent_id,referral_code) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.raw_user_meta_data->>'phone',case when lvl='buyer' then null else new.raw_user_meta_data->>'nik' end,lvl,upl,code); if lvl<>'buyer' then insert into public.referral_codes(code,owner_id,is_primary,created_by) values(code,new.id,true,new.id); end if; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin(uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=uid and role='admin') $$;
create or replace function public.create_order(p_items jsonb,p_recipient text,p_phone text,p_address text,p_postal_code text,p_shipping text,p_va_bank text) returns uuid language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); oid uuid:=gen_random_uuid(); no text; itm jsonb; pid uuid; q numeric; pr numeric; pe int; sub numeric:=0; up uuid; begin if uid is null then raise exception 'Harus login'; end if; no:='JVN'||to_char(now(),'YYMMDDHH24MISS')||substr(replace(oid::text,'-',''),1,4); select referral_parent_id into up from profiles where id=uid; insert into orders(id,order_no,buyer_id,upline_id,recipient,phone,address,postal_code,shipping_method,va_bank) values(oid,no,uid,up,p_recipient,p_phone,p_address,p_postal_code,p_shipping,p_va_bank); for itm in select * from jsonb_array_elements(p_items) loop pid:=(itm->>'product_id')::uuid;q:=(itm->>'qty')::numeric;pr:=(itm->>'unit_price')::numeric;pe:=coalesce((itm->>'points_each')::int,500); perform 1 from products where id=pid and active=true and stock>=q for update; if not found then raise exception 'Stok tidak cukup'; end if; insert into order_items(order_id,product_id,qty,unit_price,points_each) values(oid,pid,q,pr,pe); sub:=sub+q*pr; end loop; update orders set subtotal=sub,total=sub where id=oid; return oid; end $$;
create or replace function public.admin_update_order_status(p_order_id uuid,p_status text,p_tracking_no text default null) returns void language plpgsql security definer set search_path=public as $$ declare o orders%rowtype; pts bigint; begin if not is_admin() then raise exception 'Admin only'; end if; select * into o from orders where id=p_order_id for update; if p_status='paid' and o.status='pending_payment' then update products p set stock=p.stock-x.qty from (select product_id,sum(qty) qty from order_items where order_id=p_order_id group by product_id)x where p.id=x.product_id; update orders set paid_at=now() where id=p_order_id; end if; update orders set status=p_status,tracking_no=coalesce(p_tracking_no,tracking_no),completed_at=case when p_status='completed' then coalesce(completed_at,now()) else completed_at end where id=p_order_id; if p_status='completed' and o.upline_id is not null and not o.points_released then select coalesce(sum(qty*points_each),0)::bigint into pts from order_items where order_id=p_order_id; insert into points_ledger(profile_id,order_id,points,type,note) values(o.upline_id,p_order_id,pts,'referral_purchase','Reward transaksi downline'); update profiles set points_available=points_available+pts where id=o.upline_id; update orders set points_released=true where id=p_order_id; end if; end $$;
create or replace function public.request_withdrawal(p_amount_rupiah numeric,p_destination text) returns uuid language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); pts bigint:=ceil(p_amount_rupiah); wid uuid:=gen_random_uuid(); begin if p_amount_rupiah<100000 then raise exception 'Minimum withdrawal Rp100.000'; end if; perform 1 from profiles where id=uid and level<>'buyer' and points_available>=pts for update; if not found then raise exception 'Poin tidak cukup'; end if; update profiles set points_available=points_available-pts where id=uid; insert into points_ledger(profile_id,points,type,note) values(uid,-pts,'withdrawal','Pengajuan withdrawal'); insert into withdrawals(id,profile_id,points,amount_rupiah,destination) values(wid,uid,pts,p_amount_rupiah,p_destination); return wid; end $$;
create or replace function public.admin_approve_withdrawal(p_withdrawal_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin if not is_admin() then raise exception 'Admin only'; end if; update withdrawals set status='paid',processed_at=now(),processed_by=auth.uid() where id=p_withdrawal_id and status='pending'; end $$;
create or replace function public.admin_create_referral_code(p_owner_email text,p_code text) returns uuid language plpgsql security definer set search_path=public as $$ declare owner uuid; rid uuid:=gen_random_uuid(); begin if not is_admin() then raise exception 'Admin only'; end if; select p.id into owner from profiles p join auth.users u on u.id=p.id where lower(u.email)=lower(p_owner_email); if owner is null then raise exception 'Pemilik tidak ditemukan'; end if; insert into referral_codes(id,code,owner_id,created_by) values(rid,upper(trim(p_code)),owner,auth.uid()); return rid; end $$;
create or replace view public.admin_network_view as select p.id,p.full_name member_name,p.phone,p.nik,p.level member_level,p.referral_code,p.created_at joined_at,u.full_name upline_name,u.level upline_level from profiles p left join profiles u on u.id=p.referral_parent_id where p.role<>'admin';
create or replace view public.admin_referral_codes_view as select r.id,r.code,r.active,r.created_at,p.full_name owner_name,p.level owner_level from referral_codes r join profiles p on p.id=r.owner_id;
create or replace view public.admin_orders_view as select o.*,b.full_name buyer_name,u.full_name upline_name from orders o join profiles b on b.id=o.buyer_id left join profiles u on u.id=o.upline_id;
create or replace view public.admin_withdrawals_view as select w.*,p.full_name from withdrawals w join profiles p on p.id=w.profile_id;
alter table profiles enable row level security;alter table referral_codes enable row level security;alter table products enable row level security;alter table orders enable row level security;alter table order_items enable row level security;alter table points_ledger enable row level security;alter table withdrawals enable row level security;alter table support_tickets enable row level security;
create policy "profile own" on profiles for select using(id=auth.uid() or is_admin());create policy "referral read" on referral_codes for select using(active=true or is_admin());create policy "products read" on products for select using(active=true or is_admin());create policy "orders own" on orders for select using(buyer_id=auth.uid() or is_admin());create policy "items own" on order_items for select using(exists(select 1 from orders o where o.id=order_id and (o.buyer_id=auth.uid() or is_admin())));create policy "ledger own" on points_ledger for select using(profile_id=auth.uid() or is_admin());create policy "withdraw own" on withdrawals for select using(profile_id=auth.uid() or is_admin());create policy "ticket own" on support_tickets for select using(profile_id=auth.uid() or is_admin());create policy "ticket insert" on support_tickets for insert with check(profile_id=auth.uid());
grant execute on function create_order(jsonb,text,text,text,text,text,text) to authenticated;grant execute on function request_withdrawal(numeric,text) to authenticated;grant execute on function admin_update_order_status(uuid,text,text) to authenticated;grant execute on function admin_approve_withdrawal(uuid) to authenticated;grant execute on function admin_create_referral_code(text,text) to authenticated;
-- Setelah membuat akun admin, jalankan:
-- update public.profiles set role='admin',level='distributor' where id=(select id from auth.users where email='EMAIL_ADMIN_ANDA');
